---
# Define Docker Compose version.
version: "3"

# Define all the containers.
services:
  # Frontend Container.
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./myNodeRedData:/data
    ports:
     - 1880:1880
    environment:
      NODE_ENV: development